name: EmberCore
main: bnana.embercore.EmberCorePlugin
version: 1.0.0
author: bnana
commands:
  setspawn:
    description: Set the world spawn point
    permission: embercore.setspawn
  spawn:
    description: Teleport to spawn location
    permission: embercore.spawn
  hide:
    description: Hide your identity
    permission: embercore.hide.use
  live:
    description: Share a live stream link
    usage: /live <url>
    permission: embercore.live
permissions:
  embercore.setspawn:
    description: Allows use of /setspawn
    default: op
  embercore.spawn:
    description: Allows use of /spawn
    default: true
  embercore.hide.use:
    description: Allows use of /hide
    default: false
  embercore.live:
    description: Allows use of /live
    default: true